### ISSUE TITLE
Uninitialized constant Hubspot::Crm::Companies::PublicObjectSearchRequest

### ISSUE THREAD

**Issue by npcarches** [HubSpot/hubspot-api-ruby#190]
I'm using Rails 7. When I try to call 

`search_api.do_search(public_object_search_request)
`

but I can't init public_object_search_request in my rails console. Is there anyone get the same problem?
![image](https://user-images.githubusercontent.com/90299246/204776798-22f17638-632b-4ecb-94ae-0400ad64b47b.png)

**Comment by rai-hi** [comment]
I think you can just use a Hash, and it does the converting for you

```
search_request = {
  filterGroups: [
    filters: [
      {
        operator: 'EQ',
        propertyName: 'BLA',
        value: 'BLA'
      }
    ]
  ]
}
search_api.do_search(search_request) 
```

Note the camel case on `filterGroups` and `propertyName` - those were required for me.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @rai-hi 
Since version [v15.0.0](https://github.com/HubSpot/hubspot-api-ruby/releases/tag/v15.0.0), we have removed our own requires and now, in order to access custom classes, you need to call them explicitly.
Example:
```ruby
require 'hubspot/codegen/crm/companies/models/public_object_search_request'
```
This was done in order to reduce memory consumption.
Also since version [v15.0.0](https://github.com/HubSpot/hubspot-api-ruby/releases/tag/v15.0.0) do_search takes hash as an argument, more details see in [documentation](https://developers.hubspot.com/docs/api/crm/companies).
I hope this information will be useful to you.

**Comment by adomokos** [comment]
I wish this was in the README. It took me an hour of wild-goose chase:

>Since version [v15.0.0](https://github.com/HubSpot/hubspot-api-ruby/releases/tag/v15.0.0), we have removed our own requires and now, in order to access custom classes, you need to call them explicitly.
Example:

> require 'hubspot/codegen/crm/companies/models/public_object_search_request'
This was done in order to reduce memory consumption.
Also since version [v15.0.0](https://github.com/HubSpot/hubspot-api-ruby/releases/tag/v15.0.0) do_search takes hash as an argument, more details see in [documentation](https://developers.hubspot.com/docs/api/crm/companies).
I hope this information will be useful to you.
